# Generated by Django 4.0.4 on 2023-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image',
        ),
        migrations.AddField(
            model_name='images',
            name='image_og',
            field=models.ImageField(default=None, upload_to='images/og/'),
        ),
        migrations.AddField(
            model_name='images',
            name='image_processed',
            field=models.ImageField(default=None, upload_to='images/processed'),
        ),
    ]
