# Generated by Django 4.0.4 on 2023-05-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_remove_images_image_images_image_og_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image_og',
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default=None, upload_to='images/og/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='images',
            name='image_processed',
            field=models.ImageField(null=True, upload_to='images/processed'),
        ),
    ]
