# Generated by Django 4.0.4 on 2023-05-25 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_remove_images_image_og_images_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_form', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
                'db_table': 'forms',
            },
        ),
        migrations.CreateModel(
            name='Inspections',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_inspection', to='domain.forms', verbose_name='Form')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'db_table': 'inspections',
            },
        ),
        migrations.AddField(
            model_name='images',
            name='inspection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_image', to='domain.inspections', verbose_name='Inspection'),
            preserve_default=False,
        ),
    ]
